version: '3'

services:
  db:
    image: postgres
    volumes: 
      - postgres-data:/var/lib/postgresql/data
    environment: 
      - "POSTGRESQL_HOST=db"
      - "POSTGRES_USER=postgres"  
      - "POSTGRES_PASSWORD=postgres"
    ports:
      - 5432:5432
  api:
    build:
      context: ./api/
      dockerfile: Dockerfile
    command: /bin/sh -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    image: rails:dev
    volumes:
      - ./api:/myapp
      - ./api/vendor/bundle:/myapp/vendor/bundle
    environment:
      - "TZ=Asia/Tokyo"
      - "DATABASE_HOST=db"
      - "DATABASE_USER=postgres"
      - "DATABASE_PASSWORD=postgres"
    ports:
      - 3000:3000
    depends_on:
      - db
    tty: true
    stdin_open: true
  front:
    build:
      context: ./front/
      dockerfile: Dockerfile
    volumes:
      - ./front:/usr/src/app
    command: sh -c "cd /usr/src/app && yarn start"
    ports:
      - 8000:3000
volumes:
  postgres-data:
    driver: local
    
